# Site settings
title: 1X Engineering
description: A blog about random machine learning and engineering topics
author: Jiangwei Pan

# Build settings
markdown: kramdown
theme: minima
permalink: /blog/:title/

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
